version: '3.8'

services:
  # FastAPI Backend Container
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rag_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password_here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
    volumes:
      - ./api:/app/api  # Live-Reload für Development
      - ./test_documents:/app/test_documents
    networks:
      - rag_network

  # PostgreSQL + pgvector Database Container  
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_DB=rag_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rag_network

volumes:
  postgres_data:

networks:
  rag_network:
    driver: bridge 